services:
  - type: static
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    repo: https://github.com/Adhi2648/ValueGlance_Project
    branch: main

  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    repo: https://github.com/Adhi2648/ValueGlance_Project
    branch: main
