services:
  # Frontend (React App)
  - type: web
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    publishDirectory: /build
    repo: https://github.com/yourusername/your-repository
    branch: main

  # Backend (Node.js API)
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    repo: https://github.com/yourusername/your-repository
    branch: main
