services:
  - type: web
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    publishPath: /build
    repo: https://github.com/yourusername/your-repository
    branch: main

  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    repo: https://github.com/yourusername/your-repository
    branch: main
